version: 2.1
orbs:
  codecov: codecov/codecov@3.1.1
jobs:
  build:
    docker:
      - image: cimg/node:17.4.0
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - post-steps:
            - codecov/upload:
            file: {{ coverage/coverage-final.json }}
        
  